"""Added posts Model

Revision ID: 00585723c0b3
Revises: 7c59a9668d4d
Create Date: 2023-02-15 13:44:10.530531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00585723c0b3'
down_revision = '7c59a9668d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
