"""added password field

Revision ID: 7c59a9668d4d
Revises: e6c4182b3f5d
Create Date: 2023-02-15 10:50:23.071604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c59a9668d4d'
down_revision = 'e6c4182b3f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passwd', sa.String(length=126), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('passwd')

    # ### end Alembic commands ###
